accounts/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
)
from .views import dashboard_view, user_reginter, SignUpView, EditUserView, user_edit


urlpatterns = [
    # path("login/", user_login, name="login_page"),
    path("signup/", SignUpView.as_view(), name="register_page"),
    path("login/", LoginView.as_view(), name="login_page"),
    path("logout/", LogoutView.as_view(), name="logout_page"),
    path("password-change/", PasswordChangeView.as_view(), name="password_change"),
    path(
        "password-change-done/",
        PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("profile/", dashboard_view, name="profile_page"),
    path("edit-profile/", EditUserView.as_view(), name="edit_profile_page"),
    # path("edit-profile/", user_edit, name="edit_profile_page"),
]

news_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("adminman/", admin.site.urls),
    path("", include("news_app.urls")),
    path("", include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news_app/models.py
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.db import models
from django.utils.text import slugify


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=News.Status.Published)


class ActivedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Staff.Status.Active)


class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class News(models.Model):
    """
    News class
    If we delete any category, the connected news will also be deleted.
    """

    class Status(models.TextChoices):
        Draft = "DF", "Draft"
        Published = "PB", "Published"

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=300)
    body = models.TextField()
    image = models.ImageField(upload_to="news/images")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    published_time = models.DateTimeField(default=timezone.now)
    created_time = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        # Slugni titledan yaratib olish
        self.slug = slugify(self.title)

        super().save(*args, **kwargs)

    updated_time = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.Draft
    )

    objects = models.Manager()  # defauld manager
    published = PublishedManager()

    class Meta:
        ordering = ["-published_time"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("detail_page", args=[self.slug])


class Occupation(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Staff(models.Model):
    class Status(models.TextChoices):
        Active = "AT", "Active"
        Disable = "DS", "Disable"

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    staff_info = models.TextField(max_length=250)
    image = models.ImageField(upload_to="staff/images")
    occupation = models.ForeignKey(Occupation, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.Active
    )

    objects = models.Manager()  # defauld manager
    active = ActivedManager()

    # class Meta:
    #     ordering = ["-published_time"]

    def __str__(self):
        return self.first_name


class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=150)
    message = models.TextField()

    def __str__(self):
        return self.email


class Comment(models.Model):
    news = models.ForeignKey(News, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["-created_time"]

    def __str__(self):
        return f"Comment - {self.body} by {self.user}"

templates/crud/news-create.html
{% extends 'news/base.html' %}
{% load static %}

{% block title %} {{ news.title }} {% endblock title %}
{% block content %}
<div class="container custom_form">
    <div class="row">
      <div class="col-lg-12 text-center mb-5">
        <h1 class="page-title">Add new</h1>
      </div>
    </div>
    <form method="post" enctype="multipart/form-data" role="form">{% csrf_token %}
        <div>
            {{ form.as_p }}
            <button type="submit" class="btn btn-secondary px-3">Add</button>
        </div>
    </form>
  </div>
{% endblock content %}

templates/crud/news-delete.html
{% extends 'news/base.html' %}
{% load static %}

{% block title %} {{ news.title }} {% endblock title %}
{% block content %}
<main id="main">
  <section id="contact" class="contact mb-5">
    <div class="container" data-aos="fade-up">
      <div class="row">
        <div class="col-lg-12 text-center mb-5">
          <h1 class="page-title">Delete the news</h1>
        </div>
      </div>

      <div class="row gy-4">
        <div class="card" style="width: 100%%;">
          <img src="{{ news.image.url }}" class="card-img-top pt-3" alt="NOt found">
          <div class="card-body">
            <h5 class="card-title">{{ news.title }}</h5>
            <p class="card-text">{{ news.body | truncatewords:40 }}</p>
          </div>
          <form action="#" method="post" role="form" class="mb-4">{% csrf_token %}
            <div class="text-center">
              <button type="submit" class="btn btn-danger px-3">delete</button>
            </div>
          </form>
        </div>
      </div>

    </div>
  </section>

</main>
{% endblock content %}

templates/crud/news-edit.html
{% extends 'news/base.html' %}
{% load static %}

{% block title %} {{ news.title }} {% endblock title %}
{% block content %}

<main id="main">
  <section id="contact" class="contact mb-5">
    <div class="container" data-aos="fade-up">
      <div class="row">
        <div class="col-lg-12 text-center mb-5">
          <h1 class="page-title">Change the news</h1>
        </div>
      </div>

      <div class="row gy-4">
        <div class="card" style="width: 100%;">
          <img src="{{ news.image.url }}" class="card-img-top pt-3" alt="Not found">
          <div class="card-body">
            <h5 class="card-title">{{ news.title }}</h5>
            <p class="card-text">{{ news.body | truncatewords:40 }}</p>
          </div>
        </div>
      </div>

      <div class="form mt-5">
        <form action="#" method="post" anctype="multipart/form-data" role="form" class="php-email-form">{% csrf_token %}
          <div class="row">
            <div class="form-group col">
              <label for="name" class="form-label">Title</label>
              <input type="text" name="title" class="form-control" id="name" placeholder="Title" value="{{ news.title }}" required>
            </div>
          </div>
          <div class="form-group">
            <label for="body" class="form-label">Body</label>
            <textarea class="form-control" name="body" id="body" rows="5" placeholder="Message" required>{{ news.body }}</textarea>
          </div>
          <div class="form-group">
            <input type="file" name="image" class="form-control" id="name" placeholder="Title"required>
          </div>
          <div class="form-group">
            <select name="category" required="" id="id_category" class="form-select form-select-sm">
              {% for option in categories %}
                {% if option == news.category %}
                  <option value="{{ forloop.counter }}" selected="">{{ option }}</option>
                {% else %}
                  <option value="{{ forloop.counter }}">{{ option }}</option>
                {% endif %}
              {% endfor %}
            </select>
          </div>
          <div class="text-center">
            <button type="submit">Save the change</button>
          </div>
        </form>
      </div><!-- End Contact Form -->
    </div>
  </section>

</main>
    
{% endblock content %}